sensor:
  - platform: influxdb
    host: !secret influx_host
    username: !secret influx_user
    password: !secret influx_pwd
    queries:
      - name: living_humidity_raw
        unit_of_measurement: "%"
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"room" = ''living'''
        measurement: '"environment"'
        field: humidity
        database: home
  - platform: filter
    name: living_humidity
    entity_id: sensor.living_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2