sensor:
  - platform: influxdb
    host: !secret influx_host
    username: !secret influx_user
    password: !secret influx_pwd
    queries:
      - name: hallway_luminescence
        unit_of_measurement: lux
        value_template: '{{ value | round(0) }}'
        group_function: last
        where: '"room" = ''hallway'''
        measurement: '"environment"'
        field: luminescence
        database: home