homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include_dir_merge_named customize/custom
  customize_glob: !include customize/_global.yaml
  customize_domain: !include customize/_domain.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.178.0/24
        - fd00::/8
    - type: homeassistant
    - type: legacy_api_password
      api_password: !secret http_password

  packages: !include_dir_named packages

# Sets the logging level
logger:
  default: warning
  logs:
    # homeassistant.components.http: info
    custom_components.fritzbox_guestwifi: info
    # homeassistant.helpers.entity: error

system_log:
  max_entries: 50
  fire_event: true

# Enables the frontend
frontend:
  themes: !include themes.yaml


# Enables lovelace in yaml mode by default
lovelace:
  mode: yaml

# Enables the iOS companion app
ios:

# Enables configuration UI
config:

# Enables web frontend
http:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

system_health:

recorder:
  purge_keep_days: 2
  exclude:
    !include exclude_entities.yaml

# Enables support for tracking state changes over time
history:
  exclude:
    !include exclude_entities.yaml

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# External MQTT host
mqtt:
  broker: !secret mqtt_host
  discovery: True
  discovery_prefix: homeassistant

person:
  - name: Jennifer
    id: jennifer
    user_id: 0d5a676cd0ce4c8bad23121b38ecf9c8
    device_trackers:
      - device_tracker.jennifer
  - name: Dennis
    id: dennis
    user_id: 54e0dcc98328421ba486825f55855776
    device_trackers:
      - device_tracker.dennis_iphone_work

# Cloud
cloud:

# Emulated Hue
emulated_hue: !include alexa.yaml

# Groups and automation
automation: !include_dir_merge_list automations

panel_iframe:
  grafana:
    title: 'Grafana'
    url: 'http://services:3000'
    icon: mdi:chart-line
  cctv:
    title: CCTV
    url: http://motion02
    icon: mdi:cctv

zone: !include_dir_list zones
