homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include_dir_merge_named customize/custom
  customize_glob: !include customize/_global.yaml
  customize_domain: !include customize/_domain.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 127.0.0.1
        - ::1
        - 192.168.178.0/24
        - fd00::/8
    - type: homeassistant

  external_url: !secret external_url
  internal_url: !secret internal_url

  packages: !include_dir_named packages

# Sets the logging level
logger:
  default: warning
  logs:
    # homeassistant.components.http: info
    custom_components.fritzbox_guestwifi: info
    # homeassistant.helpers.entity: error

system_log:
  max_entries: 50
  fire_event: true

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest

# Enables lovelace generator
lovelace_gen:

# Enables lovelace in yaml mode by default
lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
      type: module
    - url: /local/lovelace/plant-sensor-card.js?v=16
      type: module
    - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
      type: module
  dashboards:
    lovelace-yaml:
      mode: yaml
      title: Overview
      icon: mdi:view-dashboard
      show_in_sidebar: true
      filename: ui-lovelace.yaml
    lovelace-generated:
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true

# Enables configuration UI
config:

# Enables web frontend
http:
  # Allow reverse proxy requests
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 192.168.178.72

# Enables iOS/Android app integration
mobile_app:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Provides system health information
system_health:

# Recorder settings
recorder:
  purge_keep_days: 2
  exclude:
    !include exclude_entities.yaml

# Enables support for tracking state changes over time
history:
  exclude:
    !include exclude_entities.yaml

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# External MQTT host
mqtt:
  broker: !secret mqtt_host
  discovery: True
  discovery_prefix: homeassistant

# Persons
person:
  - name: Dennis
    id: dennis
    user_id: !secret user_id_dennis
    device_trackers:
      - device_tracker.dennis_phone  # Router
      - device_tracker.iphone_work  # iOS App
  - name: Jennifer
    id: jennifer
    user_id: !secret user_id_jennifer
    device_trackers:
      - device_tracker.jennifer_phone  # Router
      - device_tracker.iphone_von_jennifer  # iOS App

# Groups
group: !include groups.yaml

# Cloud
cloud:

# Emulated Hue
emulated_hue: !include alexa.yaml

# Groups and automation
automation: !include_dir_merge_list automations

# Additional side panel stuff
# panel_iframe:
#   grafana:
#     title: 'Grafana'
#     url: 'http://services:3000'
#     icon: mdi:chart-line
#   cctv:
#     title: CCTV
#     url: http://motion02
#     icon: mdi:cctv
#   zwave:
#     title: 'Z-Wave'
#     url: http://192.168.178.73:8083/smarthome/
#     icon: mdi:z-wave

# Include custom zones
zone: !include_dir_list zones
