homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 3
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include_dir_merge_named customize/custom
  customize_glob: !include customize/_global.yaml
  customize_domain: !include customize/_domain.yaml
  auth_providers:
   - type: trusted_networks
   - type: homeassistant
   - type: legacy_api_password

  packages: !include_dir_named packages

# Sets the logging level
logger:
  default: warning
  logs:
    # homeassistant.components.http: info
    custom_components.fritzbox_guestwifi: info
    # homeassistant.helpers.entity: error

# Enables the frontend
frontend:
  themes: !include themes.yaml
  javascript_version: latest


# Enables lovelace in yaml mode by default
lovelace:
  mode: yaml

# Enables the iOS companion app
ios:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.178.0/24
    - fd00::/8

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

system_health:

recorder:
  purge_keep_days: 21
  exclude:
    !include exclude_entities.yaml

# Enables support for tracking state changes over time
history:
  exclude:
    !include exclude_entities.yaml

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# External MQTT host
mqtt:
  broker: !secret mqtt_host
  discovery: True
  discovery_prefix: homeassistant

# Setting up notifications
notify: !include_dir_list notifications

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# Emulated Hue
emulated_hue: !include alexa.yaml

# Groups and automation
group: !include groups.yaml
automation: !include_dir_merge_list automations

panel_iframe:
  router:
    title: 'Router'
    url: 'http://192.168.178.1'
    icon: mdi:router-wireless
  rpimonitor:
    title: 'RPi Monitor'
    url: 'http://services:8888'
    icon: mdi:raspberrypi
  grafana:
    title: 'Grafana'
    url: 'http://services:3000'
    icon: mdi:chart-line   

zone: !include_dir_list zones
