title: Smarthome

resources:
  - url: /local/lovelace/group-card.js?v=1
    type: js
  - url: /local/lovelace/monster-card.js?v=1
    type: js

views:
  - title: Home
    icon: mdi:home
    id: home
    badges:
      - device_tracker.dennis
      - device_tracker.jennifer
    cards:
      - id: home_tracker
        type: entities
        entities:
          - sensor.jennifer_status
          - sensor.dennis_status
      - id: home_living
        type: entities
        title: "Living room"
        entities:
          - sensor.living_temperature
          - sensor.zway_device_7_temperature
          - sensor.zway_device_7_illumination
          - binary_sensor.zway_device_7
          - switch.zway_device_4
          - switch.zway_device_5
          - switch.zway_device_17
          - light.zway_device_22
          - switch.zway_device_20
      - id: home_krymmel
        type: entities
        title: "Krymmel's End"
        entities:
          - sensor.zway_device_24_temperature
          - sensor.zway_device_24_illumination
          - binary_sensor.zway_device_24
          - switch.zway_device_13
      - id: home_bedroom
        type: entities
        title: "Bedroom"
        entities:
          - sensor.zway_device_23_temperature
          - sensor.zway_device_23_illumination
          - binary_sensor.zway_device_23
          - switch.zway_device_21
          - switch.r433_bedlamp
      - id: home_peanut
        type: vertical-stack
        cards:
          - id: home_peanut_glance
            type: picture-glance
            title: "Peanut's Playground"
            entities:
              - binary_sensor.zway_device_19
              - switch.r433_moon
              - switch.r433_miffy
            image: /local/rooms/peanut.jpg
            aspect_ratio: "16:9"
          - id: home_peanut_info
            type: horizontal-stack
            cards:
              - id: home_peanut_info_temp
                type: sensor
                entity: sensor.zway_device_19_temperature
                name: Temperature
                height: 50
              - id: home_peanut_info_lumen
                type: sensor
                entity: sensor.zway_device_19_illumination
                name: Luminescence
                height: 50
  - title: Climate
    id: climate
    icon: mdi:thermometer-lines
    badges:
      - sensor.weather_symbol
      - sensor.living_humidity
    cards:
      - id: climate_control
        type: entities
        title: Climate Controller
        entities:
          - input_select.heating_mode
          - input_boolean.splash_time
      - id: climate_ground
        type: vertical-stack
        cards:
          - id: climate_ground_temp
            type: history-graph
            title: "Ground floor (°C)"
            refresh_interval: 10
            entities:
              - sensor.living_temperature
              - sensor.zway_device_7_temperature
              - sensor.bath_downstairs_setpoint
              - sensor.living_setpoint
          - id: climate_ground_setpoints
            type: entities
            entities:
              - input_number.zway_device_12
              - input_number.zway_device_6
      - id: climate_first
        type: vertical-stack
        cards:
          - id: climate_first_temp
            type: history-graph
            title: "First floor (°C)"
            refresh_interval: 10
            entities:
              - sensor.zway_device_24_temperature
              - sensor.zway_device_19_temperature
              - sensor.zway_device_23_temperature
              - sensor.living_setpoint
              - sensor.nursery_setpoint
              - sensor.bath_upstairs_setpoint
          - id: climate_first_setpoints
            type: entities
            entities:
              - input_number.zway_device_9
              - input_number.zway_device_8
              - input_number.zway_device_11
  - title: Power
    id: power
    icon: mdi:flash-circle
    cards:
      - id: power_consumption
        type: vertical-stack
        cards:
          - type: custom:monster-card
            id: power_consumption_entities
            show_empty: False
            card:
              type: entities
              title: "Consumption"
            filter:
              include:
                - entity_id: "sensor.*_consumption"
          - id: power_consumption_graph
            type: custom:monster-card
            show_empty: False
            card:
              type: history-graph
              refresh_interval: 10
            filter:
              include:
                - entity_id: "sensor.*_consumption"
      - id: power_power
        type: vertical-stack
        cards:
          - type: custom:monster-card
            id: power_power_entities
            show_empty: False
            card:
              type: entities
              title: "Power"
            filter:
              include:
                - entity_id: "sensor.*_power"
          - id: power_power_graph
            type: custom:monster-card
            show_empty: False
            card:
              type: history-graph
              refresh_interval: 10
            filter:
              include:
                - entity_id: "sensor.*_power"
  - title: Weather
    id: weather
    icon: mdi:weather-partlycloudy
    cards:
      - id: weather_exterior
        type: entities
        title: Elmshorn
        entities:
          - sensor.date__time
          - sun.sun
          - sensor.moon
          - sensor.weather_cloudiness
      - id: weather_forecast
        type: weather-forecast
        entity: weather.openweathermap
      - id: weather_windy
        type: iframe
        url: https://embed.windy.com/embed2.html
        aspect_ratio: 75%
  - title: Monitoring
    id: monitoring
    icon: mdi:desktop-classic
    badges:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
    cards:
      - id: mon_battery
        type: custom:monster-card
        show_empty: False
        card:
          type: glance
          title: "Batteries"
        filter:
          include:
            - entity_id: "sensor.*_battery"
              
      - id: mon_system
        type: entities
        title: System
        entities:
          - sensor.processor_use
          - sensor.cpu_temp
          - sensor.memory_use_percent
          - sensor.disk_use_percent_
          - sensor.swap_use_percent
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.since_last_boot
      # - id: mon_net
      #   type: entities
      #   title: Network
      #   entities:
      #     - sensor.fritz_netmonitor
      #     - sensor.net_external_ip
      #     - sensor.net_rate_down
      #     - sensor.net_rate_up
      #     - sensor.net_rate_down_max
      #     - sensor.net_rate_up_max
      - id: mon_server
        type: entities
        title: Server
        entities:
          - binary_sensor.fritz_ping
          - binary_sensor.mediaserver_ping
          - binary_sensor.zway_ping
  - title: Settings
    id: settings
    icon: mdi:settings-outline
    cards:
      - id: settings_guest_wifi
        type: vertical-stack
        cards:
          - id: settings_guest_wifi_info
            type: markdown
            title: Guest Wifi
            content: >
              SSID: **Humletorp Gastzugang**
              
              Key: **welcome1!**
          - id: settings_guest_wifi_button
            type: entities
            entities:
              - input_boolean.guestwifi
      - type: custom:group-card
        id: settings_all_automations
        card:
          type: entities
          title: Automations
        group: group.all_automations
