title: Humletorp

views:
  - !include lovelace/views/dashboard.yaml
  - !include lovelace/views/home.yaml
  - !include lovelace/views/family.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/outdoor.yaml
  - !include lovelace/views/cctv.yaml
  - !include lovelace/views/flower.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/monitoring.yaml
  - !include lovelace/views/settings.yaml
