title: Humletorp

resources:
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /hacsfiles/lovelace-multiple-entity-row/multiple-entity-row.js
    type: module
  - url: /local/lovelace/plant-sensor-card.js?v=3
    type: module
  - url: /hacsfiles/sun-card/sun-card.js
    type: module
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module
  - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module

custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  hide_raw: true
  voice_hide: true
  options_hide: false
  exceptions:
    - conditions:
        media_query: "(max-width: 600px)"
      config:
        options_hide: true
        chevrons: false

views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/family.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/outdoor.yaml
  - !include lovelace/views/flower.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/monitoring.yaml
  - !include lovelace/views/settings.yaml
