title: Humletorp

resources:
  - url: /local/lovelace/button-card.js?v=1.10.2
    type: module
  - url: /local/lovelace/card-tools.js?v=0.4.0-dae8874
    type: js
  - url: /local/lovelace/group-card.js?v=0680a5d
    type: js
  - url: /local/lovelace/layout-card.js?v=83e2b16
    type: js
  - url: /local/lovelace/monster-card.js?v=74fb4dc
    type: js
  - url: /local/lovelace/plant-sensor-card.js?v=1
    type: module
  - url: /local/lovelace/secondaryinfo-entity-row.js?v=0.3.1
    type: module
  - url: /local/lovelace/sun-card.js?v=4.1.0
    type: module

views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/family.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/outdoor.yaml
  - !include lovelace/views/flower.yaml
  - !include lovelace/views/monitoring.yaml
  - !include lovelace/views/settings.yaml
