title: Smarthome

resources:
  - url: /local/lovelace/group-card.js?v=1
    type: js
  - url: /local/lovelace/monster-card.js?v=1
    type: js
  - url: /local/lovelace/card-tools.js?v=1
    type: js
  - url: /local/lovelace/secondaryinfo-entity-row.js?v=1
    type: module

views:
  - title: Home
    icon: mdi:home
    id: home
    badges:
      - device_tracker.dennis
      - device_tracker.jennifer
    cards:
      - id: home_tracker
        type: entities
        entities:
          - sensor.jennifer_status
          - sensor.dennis_status
      - id: home_living
        type: entities
        title: "Living room"
        show_header_toggle: False
        entities:
          - sensor.device_dht01_temperature
          - sensor.zway_device_7_temperature
          - sensor.zway_device_7_illumination
          - entity: scene.living_cinematic
            name: Cinematic
          - vacuum.pumbaa
          - entity: binary_sensor.zway_device_7
            name: "Hallway: Motion"
          - entity: binary_sensor.device_raspitouch_motion
            name: "Raspitouch: Motion"
          - entity: switch.zway_device_4
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.zway_device_4_power.state ]] W"
          - entity: switch.zway_device_5
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.zway_device_5_power.state ]] W"
          - entity: switch.zway_device_17
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.zway_device_17_power.state ]] W"
          - light.zway_device_22
          - entity: switch.zway_device_20
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.zway_device_20_power.state ]] W"
      - id: home_krymmel
        type: entities
        title: "Krymmel's End"
        show_header_toggle: False
        entities:
          - sensor.zway_device_24_temperature
          - sensor.zway_device_24_illumination
          - binary_sensor.zway_device_24
          - entity: switch.zway_device_13
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.zway_device_13_power.state ]] W"
      - id: home_bedroom
        type: entities
        title: "Bedroom"
        show_header_toggle: False
        entities:
          - sensor.zway_device_23_temperature
          - sensor.zway_device_23_illumination
          - binary_sensor.zway_device_23
          - entity: switch.zway_device_21
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.zway_device_21_power.state ]] W"
          - switch.r433_bedlamp
      - id: home_peanut
        type: vertical-stack
        cards:
          - id: home_peanut_glance
            type: picture-glance
            title: "Peanut's Playground"
            entities:
              - binary_sensor.zway_device_19
              - switch.r433_moon
              - switch.r433_miffy
            image: /local/rooms/peanut.jpg
            aspect_ratio: "16:9"
          - id: home_peanut_info
            type: entities
            entities:
              - entity: binary_sensor.zway_device_19
                name: Motion
              - entity: sensor.zway_device_19_temperature
                name: Temperature
              - entity: sensor.zway_device_19_illumination
                name: Luminescence
  - title: Home Health
    id: health
    icon: mdi:heart-pulse
    cards:
      - id: health_alert
        type: entity-filter
        entities:
          - alert.pumbaa_bin_full
          - alert.miflora_01
          - alert.miflora_02
          - alert.fitbit_dennis_blaze_out_of_sync
          - alert.fitbit_dennis_blaze_battery_low
          - alert.fitbit_dennis_water_low
        state_filter: 
          - 'on'
        show_empty: False
        card: 
          type: entities
          title: Alerts
          show_header_toggle: False
      - id: health_battery
        type: custom:monster-card
        show_empty: False
        card:
          type: glance
          title: "Batteries"
        filter:
          include:
            - entity_id: "sensor.*_battery"
      - id: health_fitbit_dennis
        title: "Fitbit - Dennis"
        type: entities
        show_header_toggle: False
        entities:
          - entity: sensor.fitbit_dennis_distance
            name: Distance (today)
          - entity: sensor.fitbit_dennis_water
            name: Hydration 
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "Goal: [[ sensor.fitbit_dennis_water_goal.state ]]"
          - entity: sensor.fitbit_dennis_blaze_battery
            name: "Blaze: battery level"
          - entity: sensor.fitbit_dennis_blaze_lastsync_mins
            name: "Blaze: Last sync"
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.fitbit_dennis_blaze_lastsync.state ]]"
      - id: health_plant_01
        type: plant-status
        entity: plant.miflora_01
      - id: health_plant_02
        type: plant-status
        entity: plant.miflora_02
      - id: health_wastebin
        title: Trash
        type: entities
        show_header_toggle: False
        entities:
          - entity: sensor.gelber_sack
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.gelber_sack.attributes.friendly_delta ]]"
          - entity: sensor.biotonne
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.biotonne.attributes.friendly_delta ]]"
          - entity: sensor.papiertonne
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.papiertonne.attributes.friendly_delta ]]"
          - entity: sensor.restabfall_2wo
            type: "custom:secondaryinfo-entity-row"
            secondary_info: "[[ sensor.restabfall_2wo.attributes.friendly_delta ]]"
      - id: health_pumbaa
        type: entities
        title: "Pumbaa"
        show_header_toggle: False
        entities:
          - entity: input_boolean.pumbaa_nightly_run
            name: "Nightly Run"
          - entity: vacuum.pumbaa
            name: "Controls"
            icon: mdi:pig
          - entity: sensor.pumbaa_battery
            name: "Battery"
          - entity: sensor.pumbaa_running_time
            name: Running time since last cleanup
            icon: mdi:timer-sand
          - entity: binary_sensor.pumbaa_bin_full
            name: Check the bin
            icon: mdi:delete-circle
          - input_datetime.pumbaa_last_bin_cleaning
          - entity: script.pumbaa_set_bin_clean
            name: "Cleaned the bin"
            icon: mdi:delete-outline
  - title: Climate
    id: climate
    icon: mdi:thermometer-lines
    badges:
      - sensor.weather_symbol
      - entity: sensor.device_dht01_humidity
        name: "Indoor Humidity"
    cards:
      - id: climate_exterior
        type: entities
        title: Elmshorn
        show_header_toggle: False
        entities:
          - sun.sun
          - sensor.moon
          - sensor.weather_cloudiness
      - id: climate_exterior_forecast
        type: weather-forecast
        entity: weather.dark_sky
      - id: climate_control
        type: entities
        title: Climate Controller
        show_header_toggle: False
        entities:
          - input_select.heating_mode
          - input_boolean.splash_time
      - id: climate_ground
        type: vertical-stack
        cards:
          - id: climate_ground_temp
            type: history-graph
            title: "Ground floor (°C)"
            refresh_interval: 10
            entities:
              - sensor.device_dht01_temperature
              - sensor.zway_device_7_temperature
              - sensor.bath_downstairs_setpoint
              - sensor.living_setpoint
          - id: climate_ground_setpoints
            type: entities
            entities:
              - input_number.zway_device_12
              - input_number.zway_device_6
      - id: climate_first
        type: vertical-stack
        cards:
          - id: climate_first_temp
            type: history-graph
            title: "First floor (°C)"
            refresh_interval: 10
            entities:
              - sensor.zway_device_24_temperature
              - sensor.zway_device_19_temperature
              - sensor.zway_device_23_temperature
              - sensor.living_setpoint
              - sensor.nursery_setpoint
              - sensor.bath_upstairs_setpoint
          - id: climate_first_setpoints
            type: entities
            entities:
              - input_number.zway_device_9
              - input_number.zway_device_8
              - input_number.zway_device_11
  # - title: Power
  #   id: power
  #   icon: mdi:flash-circle
  #   cards:
  #     - id: power_consumption
  #       type: vertical-stack
  #       cards:
  #         - type: custom:monster-card
  #           id: power_consumption_entities
  #           show_empty: False
  #           card:
  #             type: entities
  #             title: "Consumption"
  #             show_header_toggle: False
  #           filter:
  #             include:
  #               - entity_id: "sensor.*_consumption"
  #         - id: power_consumption_graph
  #           type: custom:monster-card
  #           show_empty: False
  #           card:
  #             type: history-graph
  #             refresh_interval: 10
  #           filter:
  #             include:
  #               - entity_id: "sensor.*_consumption"
  #     - id: power_power
  #       type: vertical-stack
  #       cards:
  #         - type: custom:monster-card
  #           id: power_power_entities
  #           show_empty: False
  #           card:
  #             type: entities
  #             title: "Power"
  #             show_header_toggle: False
  #           filter:
  #             include:
  #               - entity_id: "sensor.*_power"
  #         - id: power_power_graph
  #           type: custom:monster-card
  #           show_empty: False
  #           card:
  #             type: history-graph
  #             refresh_interval: 10
  #           filter:
  #             include:
  #               - entity_id: "sensor.*_power"
  - title: Monitoring
    id: monitoring
    icon: mdi:desktop-classic
    badges:
      - sensor.speedtest_download
      - sensor.speedtest_upload
      - sensor.speedtest_ping
    cards:              
      - id: mon_system
        type: entities
        title: System
        show_header_toggle: False
        entities:
          - sensor.processor_use
          - sensor.cpu_temp
          - sensor.memory_use_percent
          - sensor.disk_use_percent_
          - sensor.swap_use_percent
          - sensor.load_1m
          - sensor.load_5m
          - sensor.load_15m
          - sensor.last_boot
      # - id: mon_net
      #   type: entities
      #   title: Network
      #   entities:
      #     - sensor.fritz_netmonitor
      #     - sensor.net_external_ip
      #     - sensor.net_rate_down
      #     - sensor.net_rate_up
      #     - sensor.net_rate_down_max
      #     - sensor.net_rate_up_max
      - id: mon_server
        type: entities
        title: Server
        show_header_toggle: False
        entities:
          - binary_sensor.fritz_ping
          - binary_sensor.mediaserver_ping
          - binary_sensor.hp_printer_ping
          - binary_sensor.zway_ping
  - title: Settings
    id: settings
    icon: mdi:settings-outline
    cards:
      - id: settings_guest_wifi
        type: vertical-stack
        cards:
          - id: settings_guest_wifi_info
            type: markdown
            title: Guest Wifi
            content: >
              SSID: **Humletorp Gastzugang**
              
              Key: **welcome1!**
          - id: settings_guest_wifi_button
            type: entities
            entities:
              - input_boolean.guestwifi
      - type: custom:group-card
        id: settings_all_automations
        card:
          type: entities
          title: Automations
          show_header_toggle: False
        group: group.all_automations
