title: Humletorp

views:
  - !include lovelace/views/01_dashboard.yaml
  - !include lovelace/views/02_home.yaml
  - !include lovelace/views/03_media.yaml
  - !include lovelace/views/04_climate.yaml
  - !include lovelace/views/05_cctv.yaml
  - !include lovelace/views/06_flower.yaml
