title: Humletorp

resources:
  - url: /local/lovelace/auto-entities.js?v=e5a6b72
    type: module
  - url: /local/lovelace/button-card.js?v=3.1.1
    type: module
  - url: /local/lovelace/card-tools.js?v=d00de92
    type: js
  - url: /local/lovelace/custom-header.js?v=1.3.2
    type: module
  - url: /local/lovelace/layout-card.js?v=bc1d8f3
    type: js
  - url: /local/lovelace/multiple-entity-row.js?v=be8b9c1
    type: module
  - url: /local/lovelace/plant-sensor-card.js?v=3
    type: module
  - url: /local/lovelace/sun-card.js?v=4.1.0
    type: module
  - url: /local/lovelace/vertical-stack-in-card.js?v=0.3.2
    type: js
  - url: /local/lovelace/xiaomi-vacuum-card.js?v=3.0.1
    type: module

custom_header:
  compact_mode: true
  hide_help: true
  hide_config: true
  hide_raw: true
  voice_hide: true
  options_hide: false
  exceptions:
    - conditions:
        media_query: "(max-width: 600px)"
      config:
        options_hide: true

views:
  - !include lovelace/views/home.yaml
  - !include lovelace/views/family.yaml
  - !include lovelace/views/health.yaml
  - !include lovelace/views/media.yaml
  - !include lovelace/views/climate.yaml
  - !include lovelace/views/outdoor.yaml
  - !include lovelace/views/flower.yaml
  - !include lovelace/views/monitoring.yaml
  - !include lovelace/views/settings.yaml
