sensor:
  - platform: fritzbox_netmonitor
    host: 192.168.178.1
  - platform: template
    sensors:
      net_external_ip:
        value_template: "{{ states.sensor.fritz_netmonitor.attributes.external_ip }}"
        icon_template: mdi:nuke
      net_rate_up_raw:
        unit_of_measurement: "MBit/s"
        icon_template: mdi:upload
        value_template: "{{(states.sensor.fritz_netmonitor.attributes.transmission_rate_up * 8 / 1000 / 1000)|round(2)}}"
      net_rate_down_raw:
        unit_of_measurement: "MBit/s"
        icon_template: mdi:download
        value_template: "{{(states.sensor.fritz_netmonitor.attributes.transmission_rate_down * 8 / 1000 / 1000)|round(2)}}"
      net_rate_up_max:
        unit_of_measurement: "MBit/s"
        icon_template: mdi:progress-upload
        value_template: "{{(states.sensor.fritz_netmonitor.attributes.max_byte_rate_up * 8 / 1000 / 1000)|round(2)}}"
      net_rate_down_max:
        unit_of_measurement: "MBit/s"
        icon_template: mdi:progress-download
        value_template: "{{(states.sensor.fritz_netmonitor.attributes.max_byte_rate_down * 8 / 1000 / 1000)|round(2)}}"
  - platform: filter
    name: net_rate_up
    entity_id: sensor.net_rate_up_raw
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2
  - platform: filter
    name: net_rate_down
    entity_id: sensor.net_rate_down_raw
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0
      - filter: lowpass
        time_constant: 10
        precision: 2