person:
  - name: Jennifer
    id: jennifer
    user_id: e31c23599aa5492383e74b530933b1ef
    device_trackers:
      - device_tracker.jennifer

homeassistant:
  customize:
    person.jennifer:
      entity_picture: "/local/family/jennifer.png"