# lovelace_gen
title: Settings
id: settings
icon: mdi:settings-outline
background: var(--background-image)
cards:
  - type: vertical-stack
    id: settings_theme
    cards:
      - type: markdown
        content: "### Themes"
      - type: horizontal-stack
        cards:
        - type: custom:button-card
          entity: switch.frontend_theme_default
          name: Default
          size: 40%
        - type: custom:button-card
          entity: switch.frontend_theme_clear
          name: Day
          size: 40%
        - type: custom:button-card
          entity: switch.frontend_theme_dark
          name: Night
          size: 40%
      - type: horizontal-stack
        cards:
        - type: "custom:button-card"
          color_type: blank-card
        - type: custom:button-card
          entity: input_boolean.frontend_theme_day_night_switch
          name: "Auto switch"
          size: 40%
        - type: "custom:button-card"
          color_type: blank-card
  - id: settings_guest_wifi
    type: vertical-stack
    cards:
    - type: vertical-stack
      cards:
      - type: markdown
        content: "### Guest Wifi"
      - type: custom:layout-card
        layout: horizontal
        column_num: 2
        max_columns: 2
        max_width: [80%, 20%]
        cards:
        - id: settings_guest_wifi_info
          type: markdown
          content: >
            SSID: **Humletorp Gastzugang**
            
            Key: **welcome1!**
        - id: settings_guest_wifi_button
          type: custom:button-card
          entity: input_boolean.guestwifi
          show_name: false
          show_state: false
          size: 51px
          lock: 
            enabled: true
  - type: custom:auto-entities
    id: settings_all_automations
    card:
      type: entities
      title: Automations
      show_header_toggle: False
    filter:
      include:
        - domain: automation
    sort:
      method: name
