binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_13/switch"
    name: zway_device_13
    payload_on: "on"
    payload_off: "off"
    device_class: light

sensor:
  - platform: mqtt
    name: zway_device_13_power
    state_topic: "zway/device_13/power"
    unit_of_measurement: "W"
    icon: mdi:flash
  - platform: mqtt
    name: zway_device_13_consumption
    state_topic: "zway/device_13/consumption"
    unit_of_measurement: "kWh"
    icon: mdi:power-plug

switch:
  - platform: template
    switches:
      zway_device_13:
        value_template: "{{ is_state('binary_sensor.zway_device_13', 'on') }}"
        turn_on:
          service: rest_command.zway_switch_on
          data:
            device_id: 13
        turn_off:
          service: rest_command.zway_switch_off
          data:
            device_id: 13
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_13', 'on') %}
            mdi:lightbulb-on-outline
          {% else %}
            mdi:lightbulb-outline
          {% endif %}
