binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_20/switch"
    name: zway_device_20
    payload_on: "on"
    payload_off: "off"
    device_class: light

switch:
  - platform: template
    switches:
      zway_device_20:
        value_template: "{{ is_state('binary_sensor.zway_device_20', 'on') }}"
        turn_on:
          service: rest_command.zway_switch_on
          data:
            device_id: 20
        turn_off:
          service: rest_command.zway_switch_off
          data:
            device_id: 20
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_20', 'on') %}
            mdi:coffee
          {% else %}
            mdi:coffee
          {% endif %}
