input_number:
  zway_device_12:
    name: "Hallway heater"
    min: 6
    max: 28
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermostat

sensor:
  - platform: mqtt
    name: zway_device_12_battery
    state_topic: "zway/device_12/battery"
    device_class: battery
    unit_of_measurement: "%"

automation:
  - alias: "Hallway heater - Adjust setpoint"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_number.zway_device_12
    action:
      - service: rest_command.zway_heater_setpoint
        data_template:
          device_id: 12
          setpoint: "{{ trigger.to_state.state | int }}"
  - alias: "Hallway heater - Pull setpoint"
    initial_state: True
    trigger:
      platform: mqtt
      topic: 'zway/device_12/setpoint'
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.zway_device_12
        value: "{{ trigger.payload }}"