binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_5/switch"
    name: zway_device_5
    payload_on: "on"
    payload_off: "off"
    device_class: light

sensor:
  - platform: mqtt
    name: zway_device_5_power
    state_topic: "zway/device_5/power"
    unit_of_measurement: "W"
    value_template: '{{ value | round(1) }}'
    icon: mdi:flash
  - platform: mqtt
    name: zway_device_5_consumption
    state_topic: "zway/device_5/consumption"
    unit_of_measurement: "kWh"
    value_template: '{{ value | round(1) }}'
    icon: mdi:power-plug

switch:
  - platform: template
    switches:
      zway_device_5:
        value_template: "{{ is_state('binary_sensor.zway_device_5', 'on') }}"
        turn_on:
          service: rest_command.zway_switch_on
          data:
            device_id: 5
        turn_off:
          service: rest_command.zway_switch_off
          data:
            device_id: 5
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_5', 'on') %}
            mdi:desktop-mac-dashboard
          {% else %}
            mdi:desktop-mac
          {% endif %}
