binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_19/motion"
    name: zway_device_19
    payload_on: "on"
    payload_off: "off"
    device_class: motion

sensor:
  - platform: mqtt
    name: zway_device_19_illumination
    state_topic: "zway/device_19/illumination"
    unit_of_measurement: lux
    device_class: illuminance
  - platform: mqtt
    name: zway_device_19_temperature
    state_topic: "zway/device_19/temperature"
    unit_of_measurement: "°C"
    device_class: temperature