binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_23/motion"
    name: zway_device_23
    payload_on: "on"
    payload_off: "off"
    device_class: motion

sensor:
  - platform: mqtt
    name: zway_device_23_illumination
    state_topic: "zway/device_23/illumination"
    unit_of_measurement: lux
    device_class: illuminance
  - platform: mqtt
    name: zway_device_23_temperature
    state_topic: "zway/device_23/temperature"
    unit_of_measurement: "°C"
    device_class: temperature