binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_21/switch"
    name: zway_device_21
    payload_on: "on"
    payload_off: "off"
    device_class: light

sensor:
  - platform: mqtt
    name: zway_device_21_power
    state_topic: "zway/device_21/power"
    unit_of_measurement: "W"
    icon: mdi:flash
  - platform: mqtt
    name: zway_device_21_consumption
    state_topic: "zway/device_21/consumption"
    unit_of_measurement: "kWh"
    icon: mdi:power-plug

switch:
  - platform: template
    switches:
      zway_device_21:
        value_template: "{{ is_state('binary_sensor.zway_device_21', 'on') }}"
        turn_on:
          service: rest_command.zway_switch_on
          data:
            device_id: 21
        turn_off:
          service: rest_command.zway_switch_off
          data:
            device_id: 21
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_21', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}
