input_number:
  zway_device_9:
    name: "Gallery heater"
    min: 6
    max: 28
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermostat

sensor:
  - platform: mqtt
    name: zway_device_9_battery
    state_topic: "zway/device_9/battery"
    device_class: battery
    unit_of_measurement: "%"

automation:
  - alias: "Gallery heater - Adjust setpoint"
    initial_state: True
    hide_entity: True
    trigger:
      platform: state
      entity_id: input_number.zway_device_9
    action:
      - service: rest_command.zway_heater_setpoint
        data_template:
          device_id: 9
          setpoint: "{{ trigger.to_state.state | int }}"
  - alias: "Gallery heater - Pull setpoint"
    initial_state: True
    hide_entity: True
    trigger:
      platform: mqtt
      topic: 'zway/device_9/setpoint'
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.zway_device_9
        value: "{{ trigger.payload }}"