binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_13/switch"
    name: zway_device_13
    payload_on: "on"
    payload_off: "off"
    device_class: light

switch:
  - platform: template
    switches:
      zway_device_13:
        value_template: "{{ is_state('binary_sensor.zway_device_13', 'on') }}"
        turn_on:
          service: script.zway_switch_on
          data:
            device_id: 13
        turn_off:
          service: script.zway_switch_off
          data:
            device_id: 13
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_13', 'on') %}
            mdi:lightbulb-on-outline
          {% else %}
            mdi:lightbulb-outline
          {% endif %}
