input_number:
  zway_device_12:
    name: "Hallway heater"
    min: 6
    max: 28
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermostat

automation:
  - alias: "Hallway heater - Adjust setpoint"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_number.zway_device_12
    action:
      - service: script.zway_heater_setpoint
        data_template:
          device_id: 12
          setpoint: "{{ trigger.to_state.state | int }}"