input_number:
  zway_device_9:
    name: "Gallery heater"
    min: 6
    max: 28
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermostat

automation:
  - alias: "Gallery heater - Adjust setpoint"
    trigger:
      platform: state
      entity_id: input_number.zway_device_9
    action:
      - service: script.zway_heater_setpoint
        data_template:
          device_id: 9
          setpoint: "{{ trigger.to_state.state | int }}"