sensor:
  - platform: mqtt
    state_topic: "zway/device_22/brightness"
    name: zway_device_22

light:
  - platform: template
    lights:
      zway_device_22:
        level_template: "{{ states.sensor.zway_device_22.state|int }}"
        value_template: "{{ states.sensor.zway_device_22.state|int > 0 }}"
        turn_on:
          service: script.zway_light
          data_template:
            device_id: 22
            brightness: 25
        turn_off:
          service: script.zway_light
          data_template:
            device_id: 22
            brightness: 0
        set_level:
          service: script.zway_light
          data_template:
            device_id: 22
            brightness: "{{ brightness }}"
