binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_7/motion"
    name: zway_device_7
    payload_on: "on"
    payload_off: "off"
    device_class: motion

sensor:
  - platform: mqtt
    name: zway_device_7_illumination
    state_topic: "zway/device_7/illumination"
    unit_of_measurement: lux
    device_class: illuminance
  - platform: mqtt
    name: zway_device_7_temperature
    state_topic: "zway/device_7/temperature"
    unit_of_measurement: "°C"
    device_class: temperature