input_number:
  zway_device_6:
    name: "Bath heater"
    min: 6
    max: 28
    step: 1
    unit_of_measurement: "°C"
    icon: mdi:thermostat

automation:
  - alias: "Bathroom heater - Adjust setpoint"
    initial_state: True
    trigger:
      platform: state
      entity_id: input_number.zway_device_6
    action:
      - service: script.zway_heater_setpoint
        data_template:
          device_id: 6
          setpoint: "{{ trigger.to_state.state | int }}"
  - alias: "Bathroom heater - Pull setpoint"
    initial_state: True
    trigger:
      platform: mqtt
      topic: 'zway/device_6/setpoint'
    action:
      service: input_number.set_value
      data_template:
        entity_id: input_number.zway_device_6
        value: "{{ trigger.payload }}"