binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_17/switch"
    name: zway_device_17
    payload_on: "on"
    payload_off: "off"
    device_class: light

switch:
  - platform: template
    switches:
      zway_device_17:
        value_template: "{{ is_state('binary_sensor.zway_device_17', 'on') }}"
        turn_on:
          service: rest_command.zway_switch_on
          data:
            device_id: 17
        turn_off:
          service: rest_command.zway_switch_off
          data:
            device_id: 17
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_17', 'on') %}
            mdi:lightbulb-on-outline
          {% else %}
            mdi:lightbulb-outline
          {% endif %}
