binary_sensor:
  - platform: mqtt
    state_topic: "zway/device_4/switch"
    name: zway_device_4
    payload_on: "on"
    payload_off: "off"
    device_class: light

switch:
  - platform: template
    switches:
      zway_device_4:
        value_template: "{{ is_state('binary_sensor.zway_device_4', 'on') }}"
        turn_on:
          service: rest_command.zway_switch_on
          data:
            device_id: 4
        turn_off:
          service: rest_command.zway_switch_off
          data:
            device_id: 4
        icon_template: >-
          {% if is_state('binary_sensor.zway_device_4', 'on') %}
            mdi:television-classic
          {% else %}
            mdi:television-classic-off
          {% endif %}
