automation:
  - alias: 'Night light: Turn on in the evening'
    trigger:
      platform: sun
      event: sunset
      offset: '-00:15:00'
    action:
      service: homeassistant.turn_on
      entity_id: switch.gosund_03
  - alias: 'Night light: Turn off in the morning'
    trigger:
      platform: sun
      event: sunrise
      offset: '00:15:00'
    action: 
      service: homeassistant.turn_off
      entity_id: switch.gosund_03