automation:
  - alias: "Coffee Corner lights: Turn on when there is movement"
    trigger:
      platform: state
      entity_id: binary_sensor.zway_device_24
      to: 'on'
    condition:
      condition: numeric_state
      entity_id: sensor.zway_device_24_illumination
      below: 25
    action:
      - service: homeassistant.turn_on
        entity_id: switch.shelly_plug_s_shellyplug04_relay_0
  - alias: "Coffee Corner lights: Turn off some minutes after last movement"
    trigger:
      platform: state
      entity_id: binary_sensor.zway_device_24
      to: 'off'
      for:
        minutes: 5
    action:
      - service: homeassistant.turn_off
        entity_id: switch.shelly_plug_s_shellyplug04_relay_0
