automation:
  - alias: "Entrance lights: Turn on when there is an entrance"
    trigger:
      platform: state
      entity_id: binary_sensor.zway_device_7
      to: 'on'
    condition:
      - condition: numeric_state
        entity_id: sensor.zway_device_24_illumination
        below: 10
      - condition: template
        value_template: >
          {{
            not is_state('person.dennis', 'home')
            or (as_timestamp(now()) - as_timestamp(states.person.dennis.last_changed)) / 60 < 20
          }}
      - condition: template
        value_template: >
          {{
            not is_state('person.jennifer', 'home')
            or (as_timestamp(now()) - as_timestamp(states.person.jennifer.last_changed)) / 60 < 20
          }}
    action:
      - service: homeassistant.turn_on
        entity_id: group.lights_entrance