automation:
  - alias: "Notify: Coffee maker is ready"
    trigger:
      platform: state
      entity_id: switch.zway_device_20
      to: "on"
      for:
        minutes: 20
    action:
      - service: notify.all
        data:
          message: "Coffee maker is ready to rumble"
