automation:
  - alias: 'Notify: Washing machine has finished'
    description: ''
    use_blueprint:
      path: notify-or-do-something-when-an-appliance-like-a-dishwasher-or-washing-machine-finishes.yaml
      input:
        finishing_hysteresis: '2'
        power_sensor: sensor.zway_device_13_power
        starting_threshold: '3'
        starting_hysteresis: '2'
        finishing_threshold: '2'
        actions:
        - service: notify.all
          data:
            message: 'Washing machine is finished! Daily Costs: {{ states(''sensor.washing_machine_energy_daily_costs'')
              }} €'