automation:
  - alias: "Notify: Incoming home call"
    trigger:
      - platform: state
        entity_id: sensor.fritz_box_7530_call_monitor_fritzbox_phone
        to: ringing
    action:
      - service: notify.all
        data:
          message:
            Incoming call from {{ state_attr('sensor.fritz_box_7530_call_monitor_fritzbox_phone', 'from_name') }} ({{ state_attr('sensor.fritz_box_7530_call_monitor_fritzbox_phone', 'from') }})
