automation:
  - alias: 'Notify: Daily Maintenance overview'
    trigger:
      platform: time
      at: '20:00:00'
    action:
      - service: notify.alertmanager
        data:
          message: |
            Current alarms:
            {%- for state in states.alert %}
              {%- if state.state_with_unit == 'on' %}
              - {{ state.name }}
              {%- endif %}
            {%- endfor %}

            Low Batteries:
            {%- for state in states.sensor -%}
              {%- if state.entity_id | regex_match('.*_battery', ignorecase=TRUE) %}
              {%- if state.state | regex_match('\d+') and state.state|int < 30 %}
              - {{ state.name | lower }} is at {{state.state_with_unit}}
              {%- endif -%}
              {%- endif -%}
            {% endfor %}