binary_sensor:
  - platform: template
    sensors:
      alert_ground_bath_window_open:
        value_template: >-
          {{ 
            is_state('binary_sensor.shelly_door_window_2_shellydw01_opening', 'on') 
            and states('sensor.weather_temperature') | float < 16.0
          }}

alert:
  ground_bath_window_open:
    name: "Bath (Ground): Window is still open"
    message: "Bath (Ground): Window is still open. Current humidity: {{ states('sensor.shelly_h_t_shellyht02_humidity') }}%"
    done_message: "Bath (Ground): Window was closed. Current humidity: {{ states('sensor.shelly_h_t_shellyht02_humidity') }}%"
    entity_id: binary_sensor.alert_ground_bath_window_open
    repeat: 30  # Renotify every 30 mins
    can_acknowledge: true
    skip_first: true
    notifiers:
      - all
