#
# IMPORTANT: Automation is done by appdaemon (select_option of input_select)
# IDEA: https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/
#

input_select:
  dennis_state:
    name: Dennis
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  jennifer_state:
    name: Jennifer
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

sensor:
  - platform: template
    sensors:
      dennis_status:
        entity_picture_template: /local/family/dennis.png
        value_template: '{{ states.input_select.dennis_state.state }}'
        friendly_name: 'Dennis'
      jennifer_status:
        entity_picture_template: /local/family/jennifer.png
        value_template: '{{ states.input_select.jennifer_state.state }}'
        friendly_name: 'Jennifer'
      jonathan_status:
        entity_picture_template: /local/family/jonathan.png
        value_template: 'Near to mom'
        friendly_name: 'Jonathan'
