# MQTT Discovery:
# - dht01_temperature
# - dht01_humidity

sensor:
  - platform: filter
    name: dht01_temperature_filtered
    entity_id: sensor.dht01_temperature
    filters:
      - filter: outlier
        window_size: 4
        radius: 2.0
  - platform: filter
    name: dht01_humidity_filtered
    entity_id: sensor.dht01_humidity
    filters:
      - filter: outlier
        window_size: 4
        radius: 4.0