automation:
  - alias: "Guests Wifi: Turned On -> Send Password To Phone"
    trigger:
      platform: state
      entity_id: switch.fritzbox_7530_guest_wifi
      to: 'on'
    action:
      - service: notify.all_devices
        data:
          title: "Guest wifi is enabled"
          message: "Password: welcome1!"

alert:
  guestwifi_on:
    name: 'Guest Wifi is still on'
    entity_id: switch.fritzbox_7530_guest_wifi
    state: 'on'
    repeat: 240
    can_acknowledge: true
    skip_first: true
    notifiers:
      - all
