input_select:
  frontend_theme:
    name: Choose Theme
    options:
      - default
      - iOS Light Mode
      - iOS Dark Mode
    icon: mdi:wall

input_boolean:
  frontend_theme_day_night_switch:
    name: Automatic activation of day/night theme
    icon: mdi:theme-light-dark

switch:
  - platform: template
    switches:
      frontend_theme_default:
        value_template: "{{ is_state('input_select.frontend_theme', 'default') }}"
        icon_template: mdi:home-circle
        turn_on:
          service: input_select.select_option
          data:
            entity_id: input_select.frontend_theme
            option: "default"
        turn_off:
          service: input_select.select_option
          data:
            entity_id: input_select.frontend_theme
            option: "default"
      frontend_theme_clear:
        value_template: "{{ is_state('input_select.frontend_theme', 'iOS Light Mode') }}"
        icon_template: mdi:white-balance-sunny
        turn_on:
          service: input_select.select_option
          data:
            entity_id: input_select.frontend_theme
            option: "iOS Light Mode"
        turn_off:
          service: input_select.select_option
          data:
            entity_id: input_select.frontend_theme
            option: "iOS Light Mode"
      frontend_theme_dark:
        value_template: "{{ is_state('input_select.frontend_theme', 'iOS Dark Mode') }}"
        icon_template: mdi:weather-night
        turn_on:
          service: input_select.select_option
          data:
            entity_id: input_select.frontend_theme
            option: "iOS Dark Mode"
        turn_off:
          service: input_select.select_option
          data:
            entity_id: input_select.frontend_theme
            option: "iOS Dark Mode"

automation:
  - alias: "Theme: Switch frontend theme on select"
    id: switch_frontend_theme
    trigger:
      - platform: state
        entity_id: input_select.frontend_theme
      - platform: homeassistant
        event: start
    action:
      - service: frontend.set_theme
        data_template:
          name: "{{ states.input_select.frontend_theme.state }}"
  - alias: "Theme: Switch frontend theme on day/night cycle"
    id: day_night_theme_switch
    trigger:
      - platform: state
        entity_id: sun.sun
        to: above_horizon
      - platform: state
        entity_id: sun.sun
        to: below_horizon
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: input_boolean.frontend_theme_day_night_switch
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.frontend_theme_day_night_switch
        state: 'on'
    action:
      - service: input_select.select_option
        entity_id: input_select.frontend_theme
        data_template:
          option: >-
            {% if states.sun.sun.state == "above_horizon" %}
              iOS Light Mode
            {% else %}
              iOS Dark Mode
            {% endif %}
