binary_sensor:
  - platform: template
    sensors:
      somebody_home:
        friendly_name: "Somebody @ home"
        icon_template: >-
          {% if is_state('person.dennis', 'home') or is_state('person.jennifer', 'home') %}
            mdi:home-account
          {% else %}
            mdi:home-outline
          {% endif %}
        value_template: >-
          {{ is_state('person.dennis', 'home') or is_state('person.jennifer', 'home') }}

input_boolean:
  notify_nobody_at_home:
    name: Notify when nobody @ home
    icon: mdi:home-alert

automation:
  - alias: 'Notify: Nobody @ home'
    trigger:
      platform: state
      entity_id: binary_sensor.somebody_home
      from: 'on'
      to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.notify_nobody_at_home
        state: 'on'
    action:
      - service: notify.logs
        data:
          message: "Nobody is @home"
  - alias: 'Notify: Somebody @ home'
    trigger:
      platform: state
      entity_id: binary_sensor.somebody_home
      from: 'off'
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.notify_nobody_at_home
        state: 'on'
    action:
      - service: notify.logs
        data:
          message: "Somebody is @home"
