# https://philhawthorne.com/making-home-assistants-presence-detection-not-so-binary/

# Automation is done via appdaemon

input_select:
  dennis_state:
    name: Dennis
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away
  jennifer_state:
    name: Jennifer
    options:
      - Home
      - Just Arrived
      - Just Left
      - Away
      - Extended Away

sensor:
  - platform: template
    sensors:
      dennis_status:
        value_template: '{{ states.input_select.dennis_state.state }}'
        friendly_name: 'Dennis'
      jennifer_status:
        value_template: '{{ states.input_select.jennifer_state.state }}'
        friendly_name: 'Jennifer'

group:
  family_status:
    name: Family Status
    entities:
      - sensor.jennifer_status
      - sensor.dennis_status
