input_boolean:
  presence_state:
    name: Determine if somebody is home
    initial: on

sensor:
  - platform: template
    sensors:
      presence:
        value_template: '{{ states.input_boolean.presence_state.state }}'
        friendly_name: Presence

automation:
  - alias: Presence is on when somebody is home
    trigger:
      platform: state
      entity_id: sensor.dennis, sensor.jennifer
      from: 'not_home'
      to: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.presence_state
  - alias: Presence is off when nobody is home
    trigger:
      platform: state
      entity_id: sensor.dennis, sensor.jennifer
      from: 'home'
      to: 'not_home'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: sensor.dennis
          state: 'not_home'
        - condition: state
          entity_id: sensor.jennifer
          state: 'not_home'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.presence_state
