sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:50:AB'
    name: miflora_01
    force_update: false
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery

homeassistant:
  customize:
    sensor.miflora_01_conductivity:
      icon: mdi:flash
    sensor.miflora_01_light_intensity:
      icon: mdi:white-balance-sunny
    sensor.miflora_01_moisture:
      icon: mdi:water-percent
    sensor.miflora_01_battery:
      device_class: battery
      unit_of_measurement: "%"