sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:50:AB'
    name: miflora_01
    force_update: True
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
    scan_interval: 1200  # 20 mins
  - platform: template
    sensors:
      miflora_01_battery_status:
        value_template: >-
          {% if states('sensor.miflora_01_battery') == 'unknown' %}
            unknown
          {% else %}
            {% if states('sensor.miflora_01_battery')|int <= 10 %}
              low
            {% elif states('sensor.miflora_01_battery')|int <= 40 %}
              medium
            {% else %}
              high
            {% endif %}
          {% endif %}

homeassistant:
  customize:
    sensor.miflora_01_conductivity:
      icon: mdi:flash
    sensor.miflora_01_light_intensity:
      icon: mdi:white-balance-sunny
    sensor.miflora_01_moisture:
      icon: mdi:water-percent
    sensor.miflora_01_battery:
      device_class: battery
      unit_of_measurement: "%"