sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:4F:3D'
    name: miflora_02
    force_update: True
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
    scan_interval: 1500  # 25 mins
  - platform: template
    sensors:
      miflora_02_battery_status:
        value_template: >-
          {% if states('sensor.miflora_02_battery') == 'unknown' %}
            unknown
          {% else %}
            {% if states('sensor.miflora_02_battery')|int <= 10 %}
              low
            {% elif states('sensor.miflora_02_battery')|int <= 40 %}
              medium
            {% else %}
              high
            {% endif %}
          {% endif %}
      miflora_02_last_updated:
        friendly_name: "Last updated"
        unit_of_measurement: mins ago
        value_template: >-
          {{ (as_timestamp(now()) - as_timestamp(states.sensor.miflora_02_light.last_updated)) | int // 60 }}
        entity_id:
          - sensor.time

homeassistant:
  customize:
    sensor.miflora_02_conductivity:
      icon: mdi:flash
    sensor.miflora_02_light_intensity:
      icon: mdi:white-balance-sunny
    sensor.miflora_02_moisture:
      icon: mdi:water-percent
    sensor.miflora_02_battery:
      device_class: battery
      unit_of_measurement: "%"