sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:4F:3D'
    name: miflora_02
    force_update: True
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
    scan_interval: 1500  # 25 mins

homeassistant:
  customize:
    sensor.miflora_02_conductivity:
      icon: mdi:flash
    sensor.miflora_02_light_intensity:
      icon: mdi:white-balance-sunny
    sensor.miflora_02_moisture:
      icon: mdi:water-percent
    sensor.miflora_02_battery:
      device_class: battery
      unit_of_measurement: "%"