sensor:
  - platform: miflora
    mac: 'C4:7C:8D:6A:5A:14'
    name: miflora_04
    force_update: True
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
    scan_interval: 2100  # 35 mins
  - platform: template
    sensors:
      miflora_04_battery_status:
        value_template: >-
          {% if states('sensor.miflora_04_battery') == 'unknown' %}
            unknown
          {% else %}
            {% if states('sensor.miflora_04_battery')|int <= 10 %}
              low
            {% elif states('sensor.miflora_04_battery')|int <= 40 %}
              medium
            {% else %}
              high
            {% endif %}
          {% endif %}

homeassistant:
  customize:
    sensor.miflora_04_conductivity:
      icon: mdi:flash
    sensor.miflora_04_light_intensity:
      icon: mdi:white-balance-sunny
    sensor.miflora_04_moisture:
      icon: mdi:water-percent
    sensor.miflora_04_battery:
      device_class: battery
      unit_of_measurement: "%"