sensor:
  - platform: miflora
    mac: 'C4:7C:8D:6A:58:3C'
    name: miflora_05
    force_update: True
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery
    scan_interval: 900  # 15 mins

homeassistant:
  customize:
    sensor.miflora_05_conductivity:
      icon: mdi:flash
    sensor.miflora_05_light_intensity:
      icon: mdi:white-balance-sunny
    sensor.miflora_05_moisture:
      icon: mdi:water-percent
    sensor.miflora_05_battery:
      device_class: battery
      unit_of_measurement: "%"