sensor:
  - platform: template
    sensors:
      miflora07_battery_status:
        value_template: >-
          {% if states('sensor.miflora07_battery') == 'unknown' %}
            unknown
          {% else %}
            {% if states('sensor.miflora07_battery')|int <= 10 %}
              low
            {% elif states('sensor.miflora07_battery')|int <= 40 %}
              medium
            {% else %}
              high
            {% endif %}
          {% endif %}
      miflora07_last_updated:
        friendly_name: "Last updated"
        unit_of_measurement: mins ago
        value_template: >-
          {{ (as_timestamp(now()) - as_timestamp(states.sensor.miflora07_light_intensity.last_updated)) | int // 60 }}
        entity_id:
          - sensor.time
