plant:
  miflora_01:
    sensors:
      moisture: sensor.miflora_01_moisture
      battery: sensor.miflora_01_battery
      temperature: sensor.miflora_01_temperature
      conductivity: sensor.miflora_01_conductivity
      # brightness: sensor.miflora_01_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 15
    max_temperature: 32
    # min_brightness: 1500
    # max_brightness: 6000
  miflora_02:
    sensors:
      moisture: sensor.miflora_02_moisture
      battery: sensor.miflora_02_battery
      temperature: sensor.miflora_02_temperature
      conductivity: sensor.miflora_02_conductivity
      # brightness: sensor.miflora_02_light_intensity
    min_moisture: 15
    max_moisture: 65
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 1000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 800
    # max_brightness: 20000
  miflora_03:
    sensors:
      moisture: sensor.miflora_03_moisture
      battery: sensor.miflora_03_battery
      temperature: sensor.miflora_03_temperature
      conductivity: sensor.miflora_03_conductivity
      # brightness: sensor.miflora_03_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 35
    # min_brightness: 1000
    # max_brightness: 30000
  miflora_04:
    sensors:
      moisture: sensor.miflora_04_moisture
      battery: sensor.miflora_04_battery
      temperature: sensor.miflora_04_temperature
      conductivity: sensor.miflora_04_conductivity
      # brightness: sensor.miflora_04_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 800
    # max_brightness: 15000
  miflora_05:
    sensors:
      moisture: sensor.miflora_05_moisture
      battery: sensor.miflora_05_battery
      temperature: sensor.miflora_05_temperature
      conductivity: sensor.miflora_05_conductivity
      # brightness: sensor.miflora_05_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 1500
    # max_brightness: 45000

homeassistant:
  customize:
    plant.miflora_01:
      friendly_name: Pfeilblatt (MF01)
    plant.miflora_02:
      friendly_name: Calathea sanderiana (MF02)
    plant.miflora_03:
      friendly_name: Ficus elastica (MF03)
    plant.miflora_04:
      friendly_name: Monstera deliciosa (MF04)
    plant.miflora_05:
      friendly_name: Ficus lyrata (MF05)

alert:
  miflora_01:
    name: "Miflora 01: Problem"
    message: "{{ state_attr('plant.miflora_01', 'friendly_name') }}: {{ state_attr('plant.miflora_01', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora_01', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora_01
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: True
    skip_first: False
    notifiers:
      - ios_jennifer
  miflora_02:
    name: "Miflora 02: Problem"
    message: "{{ state_attr('plant.miflora_02', 'friendly_name') }}: {{ state_attr('plant.miflora_02', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora_02', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora_02
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: True
    skip_first: False
    notifiers:
      - ios_jennifer
  miflora_03:
    name: "Miflora 03: Problem"
    message: "{{ state_attr('plant.miflora_03', 'friendly_name') }}: {{ state_attr('plant.miflora_03', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora_03', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora_03
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: True
    skip_first: False
    notifiers:
      - ios_jennifer
  miflora_04:
    name: "Miflora 04: Problem"
    message: "{{ state_attr('plant.miflora_04', 'friendly_name') }}: {{ state_attr('plant.miflora_04', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora_04', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora_04
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: True
    skip_first: False
    notifiers:
      - ios_jennifer
  miflora_05:
    name: "Miflora 05: Problem"
    message: "{{ state_attr('plant.miflora_05', 'friendly_name') }}: {{ state_attr('plant.miflora_05', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora_05', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora_05
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: True
    skip_first: False
    notifiers:
      - ios_jennifer
