sensor:
  - platform: miflora
    mac: 'C4:7C:8D:67:50:AB'
    name: "Monstera deliciosa"
    force_update: false
    monitored_conditions:
      - moisture
      - light
      - temperature
      - conductivity
      - battery