sensor:
  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: load_1m
      - type: load_5m
      - type: load_15m
      - type: last_boot

homeassistant:
  customize:
    sensor.load_1m:
      icon: mdi:speedometer
    sensor.load_5m:
      icon: mdi:speedometer
    sensor.load_15m:
      icon: mdi:speedometer
