binary_sensor:
  - platform: stall
    name: stall_purifier_goker
    entities:
      - air_quality.pure_cool_air_quality
      - sensor.pure_cool_humidity
      - sensor.pure_cool_temperature
    threshold: 60

alert:
  stall_purifier_goker:
    name: "Goker: No sensor update"
    done_message: "Goker: Recovered"
    entity_id: binary_sensor.stall_purifier_goker
    state: 'on'
    repeat: 120  # Renotify every two hours
    can_acknowledge: true
    skip_first: false
    notifiers:
      - alertmanager
      - dennis