utility_meter:
  washing_machine_energy_daily:
    source: sensor.zway_device_13_consumption
    cycle: daily
  washing_machine_energy_monthly:
    source: sensor.zway_device_13_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      washing_machine_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.washing_machine_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      washing_machine_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.washing_machine_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
