utility_meter:
  desk_energy_daily:
    source: sensor.zway_device_5_consumption
    cycle: daily
  desk_energy_monthly:
    source: sensor.zway_device_5_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      desk_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.desk_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      desk_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.desk_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
