binary_sensor:
  - name: r433_miffy_state
    platform: command_line
    command: "curl -X GET --silent --header 'Accept: application/json' 'http://192.168.178.60:5555/devices/miffy'"
    device_class: light
    value_template: '{{value_json.state}}'
    payload_on: 'on'
    payload_off: 'off'
    scan_interval: 5

switch:
  - platform: template
    switches:
      r433_miffy:
        value_template: "{{ is_state('binary_sensor.r433_miffy_state', 'on') }}"
        turn_on:
          service: rest_command.r433_switch_on
          data:
            device_name: miffy
        turn_off:
          service: rest_command.r433_switch_off
          data:
            device_name: miffy
        icon_template: mdi:rabbit
