sensor:
  - platform: icalendar
    # Where to get it -> http://abfallkalender.regioit.de/kalender-pi/downloadfile.jsp?format=ics&jahr=2019&ort=Elmshorn&strasse=3352862&fraktion=0&fraktion=3&fraktion=4&fraktion=5&fraktion=6&fraktion=8&fraktion=9
    url: '/config/assets/2020_elmshorn_wastebin.ics'
    date_format: "%Y-%m-%dT%H:%M:%S+02:00"
    exclude: 
      - "Schadstoffsammlung in der Nähe"
      - "Restabfall 4wö Grün"

homeassistant:
  customize:
    sensor.gelbe_tonne:
      # icon: mdi:flask
      entity_picture: /local/waste_bin/yellow.png
    
    sensor.biotonne:
      # icon: mdi:biohazard
      entity_picture: /local/waste_bin/bio.png
    
    sensor.papiertonne:
      # icon: mdi:newspaper
      entity_picture: /local/waste_bin/blue.jpg
    
    sensor.restabfall_2wo:
      # icon: mdi:delete
      entity_picture: /local/waste_bin/black.png