sensor:
  - platform: yr
    name: weather
    monitored_conditions:
      - temperature
      - symbol
      - humidity
      - cloudiness

# OpenweatherMap
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: daily