sensor:
  - platform: yr
    name: weather
    monitored_conditions:
      - temperature
      - symbol
      - humidity
      - cloudiness
  - platform: template
    sensors:
      weather_iframe:
        value_template: iframe

# OpenweatherMap
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: daily