sensor:
  - platform: yr
    name: weather
    monitored_conditions:
      - temperature
      - symbol
      - humidity
      - cloudiness

# Dark Sky
weather:
  - platform: darksky
    name: Dark Sky
    api_key: !secret darksky_api_key
    mode: daily
    scan_interval: 900

homeassistant:
  customize:
    sensor.weather_cloudiness:
      friendly_name: Cloudiness
      icon: mdi:cloud-outline
    
    sensor.weather_humidity:
      friendly_name: Humidity (Outdoor)
      icon: mdi:water-percent
    
    sensor.weather_symbol:
      friendly_name: Weather
    
    sensor.weather_temperature:
      friendly_name: Temperature
    