sensor:
  - platform: yr
    name: weather
    monitored_conditions:
      - symbol
      - cloudiness
  - platform: template
    sensors:
      weather_temperature:
        friendly_name: Temperature (Outdoor)
        value_template: "{{ state_attr('weather.dark_sky', 'temperature') }}"
        device_class: temperature
        unit_of_measurement: "°C"
      weather_humidity:
        friendly_name: Humidity (Outdoor)
        value_template: "{{ state_attr('weather.dark_sky', 'humidity') | float }}"
        device_class: humidity
        unit_of_measurement: "%"
        icon_template: mdi:water-percent

# Dark Sky
weather:
  - platform: darksky
    name: Dark Sky
    api_key: !secret darksky_api_key
    mode: daily
    scan_interval: !secret darksky_interval

  - platform: darksky
    name: Dark Sky (Hourly)
    api_key: !secret darksky_api_key
    mode: hourly
    scan_interval: !secret darksky_interval

homeassistant:
  customize:
    sensor.weather_cloudiness:
      friendly_name: Cloudiness
      icon: mdi:cloud-outline
    
    sensor.weather_symbol:
      friendly_name: Weather

    