- alias: "Living room lights: Turn on when there is an entrance"
  trigger:
    platform: state
    entity_id: binary_sensor.zway_device_7
    to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.zway_device_24_illumination
      below: 10
    # State can be: Home, Just Arrived, Just Left, Away, Extended Away
    - condition: template
      value_template: "{{ not is_state('sensor.dennis_status', 'Home') }}"
    # State can be: Home, Just Arrived, Just Left, Away, Extended Away
    - condition: template
      value_template: "{{ not is_state('sensor.jennifer_status', 'Home') }}"
  action:
    - service: homeassistant.turn_on
      entity_id: group.lights_entrance