- alias: "Lights: Turn off when away"
  trigger:
    - platform: state
      entity_id: binary_sensor.somebody_home
      to: 'off'
  action:
    - service: scene.turn_on
      entity_id: scene.lights_all_off