- alias: 'Night light on in the evening'
  initial_state: True
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.zway_device_13
- alias: 'Night light off in the morning'
  initial_state: True
  trigger:
    platform: sun
    event: sunrise
    offset: '00:15:00'
  action: 
    service: homeassistant.turn_off
    entity_id: switch.zway_device_13