- alias: 'Purifier AUTO in the morning'
  trigger:
    platform: sun
    event: sunrise
    offset: '00:15:00'
  action: 
    service: dyson.set_auto_mode
    data:
      auto_mode: true
      entity_id: fan.goker