# Ficus elastica
sensor:
  - platform: template
    sensors:
      miflora01_battery_status:
        value_template: >-
          {% if states('sensor.miflora01_battery') == 'unknown' %}
            unknown
          {% else %}
            {% if states('sensor.miflora01_battery')|int <= 10 %}
              low
            {% elif states('sensor.miflora01_battery')|int <= 40 %}
              medium
            {% else %}
              high
            {% endif %}
          {% endif %}
      miflora01_last_updated:
        friendly_name: "Last updated"
        unit_of_measurement: mins ago
        value_template: >-
          {% if states('sensor.time') and states.sensor.miflora01_lastpull %}
            {{ (as_timestamp(utcnow()) - as_timestamp(strptime(states.sensor.miflora01_lastpull.state, '%Y-%m-%dT%H:%M:%S.%f'))) | int // 60 }}
          {% else %}
            unknown
          {% endif %}
