sensor:
  - platform: template
    sensors:
      miflora03_battery_status:
        value_template: >-
          {% if states('sensor.miflora03_battery') == 'unknown' %}
            unknown
          {% else %}
            {% if states('sensor.miflora03_battery')|int <= 10 %}
              low
            {% elif states('sensor.miflora03_battery')|int <= 40 %}
              medium
            {% else %}
              high
            {% endif %}
          {% endif %}
      miflora03_last_updated:
        friendly_name: "Last updated"
        unit_of_measurement: mins ago
        value_template: >-
          {{ (as_timestamp(now()) - as_timestamp(strptime(states.sensor.miflora03_lastpull.state, '%Y-%m-%dT%H:%M:%S.%f'))) | int // 60 }}
        entity_id:
          - sensor.time
