plant:
  miflora01:
    sensors:
      moisture: sensor.miflora01_moisture
      battery: sensor.miflora01_battery
      temperature: sensor.miflora01_temperature
      conductivity: sensor.miflora01_conductivity
      # brightness: sensor.miflora01_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 15
    max_temperature: 32
    # min_brightness: 1500
    # max_brightness: 6000
  miflora02:
    sensors:
      moisture: sensor.miflora02_moisture
      battery: sensor.miflora02_battery
      temperature: sensor.miflora02_temperature
      conductivity: sensor.miflora02_conductivity
      # brightness: sensor.miflora02_light_intensity
    min_moisture: 15
    max_moisture: 65
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 1000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 800
    # max_brightness: 20000
  miflora03:
    sensors:
      moisture: sensor.miflora03_moisture
      battery: sensor.miflora03_battery
      temperature: sensor.miflora03_temperature
      conductivity: sensor.miflora03_conductivity
      # brightness: sensor.miflora03_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 10
    max_temperature: 35
    # min_brightness: 1000
    # max_brightness: 30000
  miflora04:
    sensors:
      moisture: sensor.miflora04_moisture
      battery: sensor.miflora04_battery
      temperature: sensor.miflora04_temperature
      conductivity: sensor.miflora04_conductivity
      # brightness: sensor.miflora04_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 800
    # max_brightness: 15000
  miflora05:
    sensors:
      moisture: sensor.miflora05_moisture
      battery: sensor.miflora05_battery
      temperature: sensor.miflora05_temperature
      conductivity: sensor.miflora05_conductivity
      # brightness: sensor.miflora05_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 1500
    # max_brightness: 45000
  miflora06:
    sensors:
      moisture: sensor.miflora06_moisture
      battery: sensor.miflora06_battery
      temperature: sensor.miflora06_temperature
      conductivity: sensor.miflora06_conductivity
      # brightness: sensor.miflora06_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 1500
    # max_brightness: 45000
  miflora07:
    sensors:
      moisture: sensor.miflora07_moisture
      battery: sensor.miflora07_battery
      temperature: sensor.miflora07_temperature
      conductivity: sensor.miflora07_conductivity
      # brightness: sensor.miflora07_light_intensity
    min_moisture: 15
    max_moisture: 60
    min_battery: 10
    min_conductivity: 350
    max_conductivity: 2000
    min_temperature: 12
    max_temperature: 32
    # min_brightness: 1500
    # max_brightness: 45000

homeassistant:
  customize:
    plant.miflora01:
      friendly_name: Pfeilblatt (MF01)
    plant.miflora02:
      friendly_name: Calathea sanderiana (MF02)
    plant.miflora03:
      friendly_name: Ficus elastica (MF03)
    plant.miflora04:
      friendly_name: Monstera deliciosa (MF04)
    plant.miflora05:
      friendly_name: Ficus lyrata (MF05)
    plant.miflora06:
      friendly_name: Ufo (MF06)
    plant.miflora07:
      friendly_name: Glücksfeder (MF07)

alert:
  miflora01:
    name: "Miflora 01: Problem"
    message: "{{ state_attr('plant.miflora01', 'friendly_name') }}: {{ state_attr('plant.miflora01', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora01', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora01
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
  miflora02:
    name: "Miflora 02: Problem"
    message: "{{ state_attr('plant.miflora02', 'friendly_name') }}: {{ state_attr('plant.miflora02', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora02', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora02
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
  miflora03:
    name: "Miflora 03: Problem"
    message: "{{ state_attr('plant.miflora03', 'friendly_name') }}: {{ state_attr('plant.miflora03', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora03', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora03
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
  miflora04:
    name: "Miflora 04: Problem"
    message: "{{ state_attr('plant.miflora04', 'friendly_name') }}: {{ state_attr('plant.miflora04', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora04', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora04
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
  miflora05:
    name: "Miflora 05: Problem"
    message: "{{ state_attr('plant.miflora05', 'friendly_name') }}: {{ state_attr('plant.miflora05', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora05', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora05
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
  miflora06:
    name: "Miflora 06: Problem"
    message: "{{ state_attr('plant.miflora06', 'friendly_name') }}: {{ state_attr('plant.miflora06', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora06', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora06
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
  miflora07:
    name: "Miflora 07: Problem"
    message: "{{ state_attr('plant.miflora07', 'friendly_name') }}: {{ state_attr('plant.miflora07', 'problem') }}"
    done_message: "{{ state_attr('plant.miflora07', 'friendly_name') }}: Healthy"
    entity_id: plant.miflora07
    state: 'problem'
    repeat: 720  # Renotify every 12h
    can_acknowledge: true
    skip_first: true
    notifiers:
      - jennifer
