input_boolean:
  splash_time:
    name: Splash time (today)
    icon: mdi:hot-tub

automation:
  - alias: "Reset splash time"
    initial_state: True
    hide_entity: True
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.splash_time
  - alias: "Notify: Splash time"
    trigger:
      platform: time
      at: '19:15:00'
    condition:
      - condition: state
        entity_id: 'input_boolean.splash_time'
        state: 'on'
    action:
      - service: notify.notify
        data:
          message: "It's splash time, now!"