input_boolean:
  splash_time:
    name: Splash time (today)
    icon: mdi:hot-tub

automation:
  - alias: "Reset splash time"
    initial_state: True
    hide_entity: True
    trigger:
      platform: time
      at: '00:00:00'
    action:
      service: input_boolean.turn_off
      entity_id: input_boolean.splash_time
  # Better: Timeframe + on + Temperature reached
  - alias: "Notify: Splash time now"
    trigger:
      platform: time
      at: '19:00:00'
    condition:
      - condition: state
        entity_id: 'input_boolean.splash_time'
        state: 'on'
    action:
      - service: notify.all_devices
        data:
          message: "It's splash time, now!"
  - alias: "Notify: Splash time starting"
    trigger:
      platform: time
      at: '17:00:00'
    condition:
      - condition: state
        entity_id: 'input_boolean.splash_time'
        state: 'on'
    action:
      - service: notify.all_devices
        data:
          message: "Today: Splash time. Remember to close the doors!"
