sensor:
  - platform: influxdb
    host: !secret influx_host
    username: !secret influx_user
    password: !secret influx_pwd
    queries:
      - name: living_humidity
        unit_of_measurement: "%"
        value_template: '{{ value | round(1) }}'
        group_function: last
        where: '"room" = ''living'''
        measurement: '"environment"'
        field: humidity
        database: home