# Estimation of power consumption of our wall lights
utility_meter:
  stairway_energy_daily:
    source: sensor.stairway_power_consumption
    cycle: daily
  stairway_energy_monthly:
    source: sensor.stairway_power_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      stairway_current_power:
        unit_of_measurement: W
        value_template: |
          {% if is_state('switch.gosund_01', 'on') %}
            3.5
          {% else %}
            1
          {% endif %}
      stairway_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.stairway_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      stairway_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.stairway_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}

  - platform: integration
    source: sensor.stairway_current_power
    name: stairway_power_consumption
    unit_prefix: k
    round: 1
