# Estimation of power consumption of our wall lights

sensor:
  - platform: template
    sensors:
      vintage_lamp_current_power:
        unit_of_measurement: W
        value_template: |
          {% if is_state('switch.gosund_03', 'on') %}
            6
          {% else %}
            0
          {% endif %}
  - platform: integration
    source: sensor.vintage_lamp_current_power
    name: vintage_lamp_power_consumption
    unit_prefix: k
    round: 2
