# Estimation of power consumption of our Fritz!Box
utility_meter:
  fritzbox_energy_daily:
    source: sensor.fritzbox_power_consumption
    cycle: daily
  fritzbox_energy_monthly:
    source: sensor.fritzbox_power_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      fritzbox_current_power:
        unit_of_measurement: W
        value_template: |
          {{ states('sensor.time') and range(6, 9) | random | float }}
      fritzbox_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.fritzbox_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      fritzbox_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.fritzbox_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}

  - platform: integration
    source: sensor.fritzbox_current_power
    name: fritzbox_power_consumption
    unit_prefix: k
    round: 1
