# Estimation of power consumption of our wall lights

utility_meter:
  floor_lamp_energy_daily:
    source: sensor.floor_lamp_power_consumption
    cycle: daily
  floor_lamp_energy_monthly:
    source: sensor.floor_lamp_power_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      floor_lamp_current_power:
        unit_of_measurement: W
        value_template: |
          {{ (states.sensor.zway_device_22.state | int * 0.0195 + (4.5 if states.sensor.zway_device_22.state | int > 0 else 0.5)) | round(1) }}
      floor_lamp_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.floor_lamp_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      floor_lamp_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.floor_lamp_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}

  - platform: integration
    source: sensor.floor_lamp_current_power
    name: floor_lamp_power_consumption
    unit_prefix: k
    round: 1
