# Estimation of power consumption of our wall lights

sensor:
  - platform: template
    sensors:
      stairway_current_power:
        unit_of_measurement: W
        value_template: |
          {% if is_state('switch.gosund_01', 'on') %}
            2.5
          {% else %}
            0
          {% endif %}
  - platform: integration
    source: sensor.stairway_current_power
    name: stairway_power_consumption
    unit_prefix: k
    round: 2
