utility_meter:
  tv_bedroom_energy_daily:
    source: sensor.zway_device_21_consumption
    cycle: daily
  tv_bedroom_energy_monthly:
    source: sensor.zway_device_21_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      tv_bedroom_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.tv_bedroom_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      tv_bedroom_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.tv_bedroom_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
