# Estimation of power consumption of our wall lights

sensor:
  - platform: template
    sensors:
      disc_rack_current_power:
        unit_of_measurement: W
        value_template: |
          {% if is_state('switch.gosund_02', 'on') %}
            9
          {% else %}
            0
          {% endif %}
  - platform: integration
    source: sensor.disc_rack_current_power
    name: disc_rack_power_consumption
    unit_prefix: k
    round: 2
