# Estimation of power consumption of our refrigerator

utility_meter:
  refrigerator_energy_daily:
    source: sensor.refrigerator_power_consumption
    cycle: daily
  refrigerator_energy_monthly:
    source: sensor.refrigerator_power_consumption
    cycle: monthly

sensor:
  - platform: template
    sensors:
      refrigerator_current_power:
        unit_of_measurement: W
        value_template: |
          {{ states('sensor.time') and range(35, 45) | random | float }}
      refrigerator_energy_daily_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.refrigerator_energy_daily.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}
      refrigerator_energy_monthly_costs:
        unit_of_measurement: "€"
        value_template: |
          {{ ((states.sensor.refrigerator_energy_monthly.state | float *  states.input_number.energy_tariff.state | float) / 100) | round(2) }}

  - platform: integration
    source: sensor.refrigerator_current_power
    name: refrigerator_power_consumption
    unit_prefix: k
    round: 2
